[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "AWMJNFSFUB5Wcy7FE83ZJnwpLJojp6kE7QWYYA1UUywn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
